### ISSUE TITLE
Crear un streaming de tu propia webcam

### ISSUE THREAD

**Issue by tomas2387** [streamtube/proyecto#1]
Para crear un streaming con tu propia webcam:
1. Nos leemos brevemente https://developer.mozilla.org/es/docs/Web/API/Navigator.getUserMedia
2. Creamos una nueva carpeta "nuevaLibreria". 
   Creamos un nuevo archivo que se llame "script.js", "webcam.js" y otro "index.html" dentro de la carpeta "nuevaLibreria". 
   webcam.js tendrá todas las funcionalidades de la cam.
   script.js coordinará todos los scripts. se debe cargar al ultimo siempre (porque si se carga antes que otro script con funciones, no tendrá disponible esas funciones)
3. Incluimos los archivo de javascript en nuestro index.html
   
   <script src="recursos/js/webcam.js"></script>
   
   <script src="recursos/js/script.js"></script>

Pondremos los scripts al final del index.html, antes de cerrar la etiqueta body. De esta forma se cargaran los scripts cuando esté cargada la página (nos evitamos tener que poner lo de $(document).ready(function....

4 Dentro de webcam.js:

4.1. Nos dicen que la función para obtener la webcam es `getUserMedia`, pero no es cierto. 
- En versiones antiguas de chrome es navigator.webkitGetUserMedia
- En Firefox es navigator.mozGetUserMedia
- En  IE11 (supuestamente) es navigator.msGetUserMedia
  No podemos (si se puede, pero no se debe) obtener el nombre del navegador que estamos utilizando (firefox, chrome, internet explorer, etc) no podemos saber qué funcion utilizar. Lo que si sabemos es que si llamamos a `navigator.mozGetUserMedia` desde chrome nos dará false.

Por lo tanto si hacemos esto

```
if(navigator.webkitGetUserMedia) {
         //si entra aquí es chrome! 
         //guardamos la funcion propia de chrome en una variable unica
         navigator.getMedia = navigator.webkitGetUserMedia;
}
else if (navigator.mozGetUserMedia) {
        //si entra aquí es firefox
        //guardamos la funcion propia de firefox en una variable unica
        navigator.getMedia = navigator.mozGetUserMedia;
}
```

Sabremos en qué navegador estamos.

Tambien lo podemos poner reducido así:

```
navigator.getMedia = (navigator.webkitGetUserMedia || navigator.mozGetUserMedia);
```

Entonces, primero pondremos esto:

```
navigator.getMedia = ( navigator.getUserMedia ||
                       navigator.webkitGetUserMedia ||
                       navigator.mozGetUserMedia ||
                       navigator.msGetUserMedia);
```

Si te fijas hemos guardado en `navigator.getMedia` la función correcta.

4.2 A continuación crearemos una funcion que se llame, por ejemplo, "pedirWebCam". Si se te ocurre otro nombre mejor, pues tu mismo.

``` js
function pedirWebCam() {

} 
```

4.3 La funcion pedirWebCam recibe dos parametros. Una función cuando todo ha ido bien; y una función cuando todo ha ido mal.

``` js
function pedirWebCam(callbackTodoBien, callbackTodoMal) {

} 
```

4.4 Llamamos a nuestra funcion navigator.getMedia dentro de pedirWebCam

``` js
function pedirWebCam(callbackTodoBien, callbackTodoMal) {
     navigator.getMedia({video: true,audio: true}, callbackTodoBien, callbackTodoMal);
} 
```

5  En el archivo script.js que hemos creado, 

```
pedirWebCam(
function(streamWebCam) {
  var video = document.createElement("video");
  video.src=streamWebCam;
  document.body.appendChild(video);
},
function(error) {
   alert("Tu navegador es un poco mierdoso porque no detecta la webcam. Error: "+error);
});
```

**Comment by Ninjacu** [comment]
Ya he hecho todos estos pasos pero ahora cuando entro me pone Muy Bien etc y no hay cámara XD

**Comment by tomas2387** [comment]
Ya se lo que falta. Mira este ejemplo
http://stackoverflow.com/questions/12854825/hello-world-on-webcam-capturing-in-html5-fails-to-work

**Comment by Ninjacu** [comment]
He conseguido que salga el vídeo! Pero cuando intentas acceder a la misma url desde otro navegador te da error en la camara

**Comment by Ninjacu** [comment]
Mañana espero acabarlo todo no creo que falte mucha cosa pero no es que pasa con eso de que sólo puedes entrar a la vez en un navegador

**Comment by tomas2387** [comment]
Creo que con chrome y solo con chrome hay que poner
video.src = window.URL.createObjectURL(stream);

Con firefox es

video.mozSrcObject = stream;

Y hay otros navegadores que tienes que hacerlo así:

video.srcObject = stream;

Ahora te preguntarás: Y cómo sé que navegador estoy usando ahora desde
javascript?? No tienes

que saberlo. Lo único que tienes que saber es si el navegador que
estás usando, puede o no

puede usar video.src o video.mozSrcObject o video.srcObject.

Para saber cómo hacerlo bien independiente del navegador, tendrás que
hacer esto:

```
    if (typeof video.srcObject !== 'undefined') {

        video.srcObject = stream;
    } else if (typeof video.mozSrcObject !== 'undefined') {

        video.mozSrcObject = stream;
    } else if (typeof video.src !== 'undefined') {

        video.src = *window.*URL.createObjectURL(stream);

    } else {

        throw new Error('Error es imposible reproducir el stream
```

en el video! (¿¿Que navegador usas??)');

```
    }
```

Esta serie de if, else if, y else, nos detectan primero, si
video.srcObject está definido: Si lo está,
pues usamos ese. Si no lo está, comprobamos si está definido
video.mozSrcObject, si lo está usamos

ese, si no lo está, seguimos con el siguiente (el de chrome) y así. Si
ninguno está definido lanzamos un
error que es imposible reproducir el stream.

Prueba con eso.

El 9 de marzo de 2014, 20:59, Ninjacu notifications@github.com escribió:

> Mañana espero acabarlo todo no creo que falte mucha cosa pero no es que
> pasa con eso de que sólo puedes entrar a la vez en un navegador
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/streamtube/proyecto/issues/1#issuecomment-37137064
> .

## 

Tomás.

**Comment by Ninjacu** [comment]
Bueno yo he puesto este código pero solo me funciona en Chrome. En teoría cuando hay dos en la página se tienen que ver dos WebCams? Me estoy liando mucho con el código este si puedes algun día Skype avisame...

**Comment by tomas2387** [comment]
No.
De momento lo que has hecho es para una unica persona viendose a si misma en su propia webcam.

**Comment by Ninjacu** [comment]
Okey pues eso está hecho creo... Míratelo hoy si puedes y me dices algo por Skype si estoy conectado

**Comment by tomas2387** [comment]
Es correcto y mucho mejor de lo que te habia puesto yo. muy bien
