### ISSUE TITLE
Crear extensión de chrome para streamtube

### ISSUE THREAD

**Issue by tomas2387** [streamtube/proyecto#14]
Crear el principio de una extensión para chrome. 

La idea es que al final, la gente se instale esta extensión y cuando esté viendo un video de youtube lo pueda ver con sus amigos en streamtube.  
Algo así:
## ![playground 1](https://f.cloud.github.com/assets/2075943/2404187/2ff4bd56-aa38-11e3-9025-0501d20da211.png)

Para crear la extensión (y que se cargue en chrome)
Leer y hacer los pasos indicados en http://developer.chrome.com/extensions/getstarted

**Comment by Guillemv98** [comment]
hola ya he terminado y puedes revisarlo, he hecho un icono para la extensión también. Adiós!

**Comment by tomas2387** [comment]
Me gusta mucho el icono!
