### ISSUE TITLE
Cambiar el diseño de los videos de la webcam

### ISSUE THREAD

**Issue by tomas2387** [streamtube/proyecto#4]
¿Es realmente posible cambiar el diseño de los botones de los videos?

**Comment by Ninjacu** [comment]
¿A qué videos te refieres? WebCam o de YouTube

**Comment by Ninjacu** [comment]
Ya está casi acabada! Solo falta insertar los botones en el video, que por ahora están fuera, pero eso no es mucho trabajo.

**Comment by tomas2387** [comment]
Te he enviado un mensaje por el skype
Yo creo que es así, como lo pone en la respuesta de esta pregunta en
stackoverflow
http://stackoverflow.com/questions/10422105/add-text-above-html5-video

Si yo le pongo position absolute o position relative a un elemento, tendré
disponibles y funcionando 4 reglas más: top, bottom, right y left.

La teoria dice que si tu defines el estilo de un elemento con position:
absolute
lo que hace es buscar al elemento padre mas proximo con un position:
relative, y a partir de este padre, cogerá todas las referencias de la
posicion.

Es decir,

<div id="padre">
     <div id="hijo"></hijo>
</div>

Imagina que padre tiene un position relative y hijo tiene un position
absolute.

#padre {
    position:relative;
}
#hijo {
    position:absolute;
}

si tu le pones al hijo top:10px lo que hará es ponerse a 10px del padre por
la parte de arriba.

¿Se entiende?
Eso tienes que hacer con los botones y el video. Así los botones seguirán
siempre con el video-

El 18 de marzo de 2014, 19:34, Ninjacu notifications@github.com escribió:

> Ya está casi acabada! Solo falta insertar los botones en el video, que por
> ahora están fuera, pero eso no es mucho trabajo.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/streamtube/proyecto/issues/4#issuecomment-37970835
> .

## 

Tomás.
